apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  selector:
    matchLabels:
      app: search
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - image: peterhell95/search:jenkins
          imagePullPolicy: Always
          name: search
          ports:
            - containerPort: 8083
