spring:
  profiles: container
  datasource:
    driver-class-name: org.postgresql.Driver
    password: kDiEBpvGUnvzaMUjtDnr
    url: jdbc:postgresql://bzgpd7ulltvarulkzeje-postgresql.services.clever-cloud.com:5311/bzgpd7ulltvarulkzeje
    username: umf81ankxvy9lsv039cv
    hikari:
      maximum-pool-size: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false  
    show-sql: true
server:
  port : 8083
        
